### PR TITLE
Update token contracts

### PR DESCRIPTION
**Pull request by zjb0807**

### CODE REVIEW

**Review by xlc — APPROVED** [review]

**Comment by ermalkaleci** [comment]
@zjb0807 I think we should keep the rest untouched to match with precompile addresses

**Comment by zjb0807** [comment]
> @zjb0807 I think we should keep the rest untouched to match with precompile addresses

https://github.com/AcalaNetwork/Acala/blob/9b1a7b7aa84b98621bddc7efdc0b3a6875cdb380/runtime/common/src/precompile/mod.rs#L71-L76

```
pub const MULTI_CURRENCY: H160 = H160(hex!("0000000000000000000000000000000000000400"));
pub const NFT: H160 = H160(hex!("0000000000000000000000000000000000000401"));
pub const EVM: H160 = H160(hex!("0000000000000000000000000000000000000402"));
pub const ORACLE: H160 = H160(hex!("0000000000000000000000000000000000000403"));
pub const SCHEDULER: H160 = H160(hex!("0000000000000000000000000000000000000404"));
pub const DEX: H160 = H160(hex!("0000000000000000000000000000000000000405"));
```

We don't need the `Token` now (and should not need the `NFT`). It doesn't match now.

**Comment by ermalkaleci** [comment]
@zjb0807 we can start from 802 and leave 800 and 801 empty

**Comment by zjb0807** [comment]
@ermalkaleci That would be a little weird. I want the numbers to be consecutive

**Review by ermalkaleci — APPROVED** [review]

**Pull request merged**
