### PR TITLE
Remove foreign currencies

### PR DESCRIPTION
**Pull request by shaunxw**

### CODE REVIEW

**Review by xlc — APPROVED** [review]

**Comment by zjb0807** [comment]
Token.json is automatically generated, is it to be maintained manually now?

**Comment by shaunxw** [comment]
> Token.json is automatically generated, is it to be maintained manually now?

No there should not be any change for contract generation process. When would the `Token.json` be generated, during the build phase of Acala repo?

**Comment by zjb0807** [comment]
> > Token.json is automatically generated, is it to be maintained manually now?
> 
> No there should not be any change for contract generation process. When would the `Token.json` be generated, during the build phase of Acala repo?

https://github.com/AcalaNetwork/Acala/blob/master/scripts/generate-tokens-and-predeploy-contracts.sh

@xlc 
It is better to maintain manually now because the lp token needs to be added.

**Comment by shaunxw** [comment]
> > > Token.json is automatically generated, is it to be maintained manually now?
> > 
> > 
> > No there should not be any change for contract generation process. When would the `Token.json` be generated, during the build phase of Acala repo?
> 
> https://github.com/AcalaNetwork/Acala/blob/master/scripts/generate-tokens-and-predeploy-contracts.sh

Do we run this script manually, or it's triggered in Acala CI?

**Comment by zjb0807** [comment]
> > > > Token.json is automatically generated, is it to be maintained manually now?
> > > 
> > > 
> > > No there should not be any change for contract generation process. When would the `Token.json` be generated, during the build phase of Acala repo?
> > 
> > 
> > https://github.com/AcalaNetwork/Acala/blob/master/scripts/generate-tokens-and-predeploy-contracts.sh
> 
> Do we run this script manually, or it's triggered in Acala CI?

https://github.com/AcalaNetwork/Acala/actions/workflows/publish.yml

Acala CI by manually.

**Comment by shaunxw** [comment]
Replaced by CI commit https://github.com/AcalaNetwork/predeploy-contracts/commit/215277d2e66c3e733f3cdb45c5b811910be21916

**Pull request closed without merging**
